name: Build

on:
  push:
    branches: 
      - "main" 
      - "develop" 
      - "feature/*" 
  pull_request:
    branches: [ "main, develop" ]

jobs:
    
  version:
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
  
  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: cd discord-bot && mvn -B package --file pom.xml
    
            
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/jfwenisch/discord-experiencebot
        
    - name: list files root
      run: ls -l
      
    - name: list files target
      run: cd discord-bot/target && ls -l
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/jfwenisch/discord-experiencebot:${{needs.version.outputs.tag}}
          ghcr.io/jfwenisch/discord-experiencebot:latest
        labels: ${{ steps.meta.outputs.labels }}


  release:
    runs-on: ubuntu-latest
    needs:  [version, build]
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{needs.version.outputs.tag}}
        name: Release ${{needs.version.outputs.tag}}
        body: ${{needs.version.outputs.changelog}}
